# Generated by Django 5.2.3 on 2025-06-13 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerIDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.IntegerField(default=0)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.department', verbose_name='Assigned Department')),
            ],
        ),
    ]
