# Generated by Django 5.2.2 on 2025-06-16 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
        ('grievance_app', '0001_initial'),
        ('officer', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'officer_flowstage',
            },
        ),
        migrations.CreateModel(
            name='GrievanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'officer_grievanceassignment',
            },
        ),
        migrations.CreateModel(
            name='GrievanceFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'officer_grievanceflow',
            },
        ),
        migrations.CreateModel(
            name='GrievanceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'officer_grievancestatuslog',
            },
        ),
        migrations.CreateModel(
            name='GrievanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=20)),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'officer_grievancetransfer',
            },
        ),
        migrations.RemoveConstraint(
            model_name='officerprofile',
            name='unique_hod_per_department',
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.department'),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='officeridtracker',
            table='officer_officeridtracker',
        ),
        migrations.AlterModelTable(
            name='officerprofile',
            table='officer_officerprofile',
        ),
        migrations.AddField(
            model_name='flowstage',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.department'),
        ),
        migrations.AddField(
            model_name='flowstage',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.officerprofile'),
        ),
        migrations.AddField(
            model_name='grievanceassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievanceassignment',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='grievanceassignment',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.officerprofile'),
        ),
        migrations.AddField(
            model_name='grievanceflow',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.department'),
        ),
        migrations.AddField(
            model_name='grievanceflow',
            name='current_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.officerprofile'),
        ),
        migrations.AddField(
            model_name='grievanceflow',
            name='grievance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='flowstage',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.grievanceflow'),
        ),
        migrations.AddField(
            model_name='grievancestatuslog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievancestatuslog',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='from_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='core_app.department'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='to_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='core_app.department'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='transferred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
