# Generated by Django 5.2.3 on 2025-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='post_images/')),
                ('read_comments', models.BooleanField(default=False)),
                ('time_limit', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
