# Generated by Django 5.1.7 on 2025-08-02 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0006_collectororder_collectororderassignment'),
        ('core_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictOfficerIDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.district')),
            ],
            options={
                'db_table': 'district_officer_id_tracker',
            },
        ),
        migrations.CreateModel(
            name='DistrictOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile image for the district officer.', null=True, upload_to='DO_profiles/', verbose_name='Profile Picture')),
                ('official_address', models.TextField(default='NA', verbose_name='Office Address')),
                ('created_by', models.ForeignKey(default='COLL20IDK', on_delete=django.db.models.deletion.PROTECT, to='collector.collectorprofile')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='district_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'district_officer_profile',
                'ordering': ['-assigned_on'],
            },
        ),
    ]
