# Generated by Django 5.2.2 on 2025-06-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
        ('district_officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtofficerprofile',
            options={'ordering': ['-assigned_on']},
        ),
        migrations.AddField(
            model_name='districtofficerprofile',
            name='officer_id',
            field=models.CharField(default='NA', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districtofficerprofile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.district'),
        ),
        migrations.AlterModelTable(
            name='districtofficerprofile',
            table='district_officer_profile',
        ),
        migrations.CreateModel(
            name='DistrictOfficerIDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.district')),
            ],
        ),
    ]
