# Generated by Django 5.1.7 on 2025-08-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_collectororder_collectororderassignment'),
        ('district_officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtofficerprofile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.collectorprofile'),
        ),
    ]
