# Generated by Django 5.2.2 on 2025-06-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_officer', '0002_alter_districtofficerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtofficerprofile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
