# Generated by Django 5.2.2 on 2025-06-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
        ('district_officer', '0003_districtofficerprofile_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtofficerprofile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.district', unique=True),
        ),
    ]
