# Generated by Django 5.2.2 on 2025-06-21 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
        ('district_officer', '0004_alter_districtofficerprofile_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtofficerprofile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.district'),
        ),
        migrations.AddConstraint(
            model_name='districtofficerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('district__isnull', False)), fields=('district',), name='uniq_officer_per_district'),
        ),
    ]
