# Generated by Django 5.2.2 on 2025-06-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_officer', '0005_alter_districtofficerprofile_district_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='districtofficeridtracker',
            table='district_officer_id_tracker',
        ),
    ]
