# Generated by Django 5.2.2 on 2025-06-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
        ('district_officer', '0006_alter_districtofficeridtracker_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='districtofficerprofile',
            name='uniq_officer_per_district',
        ),
        migrations.AlterField(
            model_name='districtofficerprofile',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.district'),
        ),
    ]
