# Generated by Django 5.1.7 on 2025-06-17 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_initial'),
        ('core_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='handover_notes',
            field=models.TextField(blank=True, help_text='Optional remarks during handover.', null=True, verbose_name='Handover Notes'),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active collector per district.', verbose_name='Is Active Collector'),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='tenure_end',
            field=models.DateField(blank=True, null=True, verbose_name='Tenure End Date'),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.district', verbose_name='Administered District'),
        ),
        migrations.AddConstraint(
            model_name='collectorprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('district',), name='unique_active_collector_per_district'),
        ),
    ]
