# Generated by Django 5.2.2 on 2025-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_collectorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
