# Generated by Django 5.1.7 on 2025-08-02 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_collectorprofile_is_first_login'),
        ('core_app', '0002_initial'),
        ('officer', '0003_flowstage_grievanceassignment_grievanceflow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('remark', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='admin_orders/')),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(related_name='collector_orders', to='core_app.department')),
            ],
            options={
                'db_table': 'collector_order',
            },
        ),
        migrations.CreateModel(
            name='CollectorOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.officerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='collector.collectororder')),
            ],
            options={
                'db_table': 'collector_order_assignment',
                'unique_together': {('order', 'officer')},
            },
        ),
    ]
