# Generated by Django 5.2.3 on 2025-06-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Department Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='District Code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='District Name')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
    ]
