# Generated by Django 5.2.3 on 2025-06-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuserprofile',
            name='announcements_email',
            field=models.BooleanField(default=True, verbose_name='Email: Announcements'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark Mode'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='data_collection',
            field=models.BooleanField(default=True, verbose_name='Allow Data Collection'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='high_contrast_mode',
            field=models.BooleanField(default=False, verbose_name='High Contrast Mode'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Password Change'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='new_messages_push',
            field=models.BooleanField(default=True, verbose_name='Push: New Messages'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='newsletter_email',
            field=models.BooleanField(default=False, verbose_name='Email: Newsletter'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='personalization',
            field=models.BooleanField(default=True, verbose_name='Enable Personalization'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='status_updates_email',
            field=models.BooleanField(default=True, verbose_name='Email: Complaint Status Updates'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50, verbose_name='Timezone'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Two-Factor Authentication'),
        ),
        migrations.AddField(
            model_name='publicuserprofile',
            name='urgent_updates_push',
            field=models.BooleanField(default=True, verbose_name='Push: Urgent Updates'),
        ),
    ]
