# Generated by Django 5.2.3 on 2025-06-21 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
        ('user', '0002_publicuserprofile_announcements_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuserprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='panchayath',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Panchayath'),
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='thaluk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thaluk'),
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Village'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='complaint_documents/%Y/%m/%d/')),
                ('applicant_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('applicant_address', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.district', verbose_name='District')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'PUBLIC'}, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
