# Generated by Django 5.2.3 on 2025-06-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_publicuserprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='announcements_email',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='data_collection',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='high_contrast_mode',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='last_password_change',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='new_messages_push',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='newsletter_email',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='personalization',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='status_updates_email',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='urgent_updates_push',
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='date_of_birth',
            field=models.DateField(default='', verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='', max_length=10, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='panchayath',
            field=models.CharField(default='', max_length=100, verbose_name='Panchayath'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='thaluk',
            field=models.CharField(default='', max_length=100, verbose_name='Thaluk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='village',
            field=models.CharField(default='', max_length=100, verbose_name='Village'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
