# Generated by Django 5.2.2 on 2025-06-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
