# Generated by Django 5.2.3 on 2025-06-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0002_grievance_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='applicant_address',
            field=models.TextField(help_text='Provide full residential address', verbose_name='Applicant Address'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='applicant_name',
            field=models.CharField(max_length=100, verbose_name='Applicant Name'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='GrievanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='grievance_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grievance_app.grievance')),
            ],
        ),
    ]
